post http://localhost:8080/api/favorites
Content-Type: application/json

{
    "id":1,
    "poster":"tryPoste.jpg",
    "title":"titleTrial"
}
###
use to login before testing api

http://localhost:8080/static/login.html


.env extra fields
LOGGING_FORMAT=dev
SECRET=asdsadfd234sad324324sad
KEY=sid
PORT=8080